### PR TITLE
Add Hypothesis[django]

### PR DESCRIPTION
**Pull request by jamescooke**
Use Hypothesis's django extras package and call for an `example`.

### CODE REVIEW

**Comment by jamescooke** [comment]
The reason that Hypothesis[django] is RED :red_circle: is because `model(Item).example()` does not reliably generate valid data. There could be two solutions, if either were provided by the library then it would be bumped up to GREEN :green_heart: ...
- Call `example` so that it returns only valid data? Something like `example(valid=True)`.
  
  This would mean that the `do_draw` function here https://github.com/HypothesisWorks/hypothesis-python/blob/master/src/hypothesis/extra/django/models.py#L174-L175 would be called multiple times if the data was invalid.
- Add some kind of inline `assume`. This would look something like `model(Item).example().assume('full_clean')` which would mean that the generated instance's `full_clean` passing would be a condition of returning the instance.

Maybe either or both of these exist already and I've missed them - that would be optimal :smile:

**Comment by DRMacIver** [comment]
You could do model(Item).filter(lambda item: item.full_clean()).

I actually thought this was already happening, but I think maybe that was in a pull request that got abandoned.

**Comment by DRMacIver** [comment]
Hmm. Actually that won't work perfectly. There will still be invalid items in the database, but it won't return them from the example.

**Comment by jamescooke** [comment]
@DRMacIver Thanks for checking this out. I feel sad that this doesn't work with Hypothesis out of the box (yet). Hopefully I'll be able to look some more at Hypothesis[django] and see if there's any quick win that could mean that `example(valid=True)` could become a reality.

If you find that abandoned PR please stick it on here or tweet it to me - I'd be excited to look it over.

**Comment by jamescooke** [comment]
Note to self - abandoned PR in Hypothesis is here: https://github.com/HypothesisWorks/hypothesis-python/pull/335

**Pull request merged**
